import { version } from "react";

export const labels = {
  loginAccount:"Login Account",
  siliconBricks:"Silicon Bricks",
  loginToAccount:"Log in to your account to continue",
  loginToSiliconBricks:"Login to Silicon Bricks",
  email:"Email",
  password:"Password",
  username:"Username",
  enter:"Enter",
  emailIsRequired:"Email is required",
  enterAValidEmail:"Enter a valid email",
  passwordIsRequired:"Password is required",
  passwordLength:"Password must be at least 6 characters long",
  forgotPassword:"Forgot Password?",
  login:"Login",
  google:"Google",
  dontHaveAnAccount:"Don't have an account?",
  signUp:"Sign Up",
  welcomeToSiliconBricks:"Welcome to Silicon Bricks",
  createNewSiliconBricksAccount:"Create a new Silicon Bricks account",
  enterEmail:"Enter your email",
  enterPassword:"Enter your password",
  confirm:"Confirm",
  pleaseConfirmYourPassword:"Please confirm your password",
  passwordDontMatch:"Passwords don't match",
  alreadyHaveAccount:"Already have an account?",
  signIn:"Sign In",
  enterYourRegisteredEmail:"Enter your registered email",
  loginInstead:"Login instead",
  sendOtp:"Send OTP",
  home:"Home",
  organization:"Organization",
  profile:"Profile",
  projects:"Projects",
  settings:"Settings",
  notification:"Notification",
  language:"Language",
  appearance:"Appearance",
  support:"Support",
  help:"Help",
  about:"About",
  logout_title:"Logout",
  logout_msg:"Are you sure you want to logout?",
  cancel:"Cancel",
  logout:"Logout",
  project:"Project",
  user:"user",
  RolesPermission:"Roles",
  enterCode:"Enter Code",
  enterCodeMsg:"Enter the code we sent to your email",
  errorMessage:"Invalid OTP",
  loginCode:"Login Code",
  searchTeam:"Search Team",
  createOraganization:"Create Organization",
  copyRight:"Copyright © 2023 Silicon Bricks. All rights reserved.",
  termsOfService:"Terms of Service",
  privacyPolicy:"Privacy Policy",
  version:"Version",
  projectName : "Project Name",
  description : "Description",
  offerPromotions : "Offer & Promotions",
  module : "Module",
  coupons : "Coupons",
  subscriptions : "Subscriptions",
  searchOrganization:"Search Organization",
  packages : "Packages",
  plans:"Plans",
  createPlans : "Create Plans",
  permission : "Permission",
  searchPackage:"Search Package",
  searchModule:"Search Module",
  searchCoupon:"Search Coupon",
  searchUser:"Search User",
};
