schema:
  - 'http://192.168.1.35:5001/graphql'
documents: './graphql/*.graphql'
generates:
  graphql/generated.ts:
    plugins:
      - typescript
      - typescript-operations
      - typed-document-node
  graphql/introspection.json:
    plugins:
      - introspection
